version: "3.9"

services:
  nginx:
    init: true
    image: moveyourdigital/nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
    
    environment:
      NGINX_HOST: 127.0.0.1
      NGINX_PORT: 80
      FASTCGI_HOST: wordpress
      FASTCGI_PORT: 9000

    ports: 
      - 8080:80

    command: [
      "wait-for-it", "-t", "0", "wordpress:9000", "--", 
      "/docker-entrypoint.sh", 
      "nginx", "-g", "daemon off;"
    ]


  mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  memcached:
    image: memcached:alpine

  wordpress:
    init: true
    build:
      context: .
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /** Enables cache */
        define( 'WP_CACHE', getenv_docker('WP_CACHE', false) );
        
        /** Disables auto updates on core */
        define( 'WP_AUTO_UPDATE_CORE', getenv_docker('WP_AUTO_UPDATE_CORE', false) );
        
        /** Disables WP cronjobs and uses crontab */
        define( 'DISABLE_WP_CRON', getenv_docker('WP_AUTO_UPDATE_CORE', true) );
        
        /**#@+
        * S3 Uploads settings
        */
        define( 'S3_UPLOADS_USE_LOCAL', true );

    volumes:
      - ./html:/var/www/html

volumes:
  db_data:
