name: Push Latest WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.moveyourdigital.dev
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          network: host
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: registry.moveyourdigital.dev/wordpress:6.0-php8.0-fpm
          cache-from: type=registry,ref=wordpress:6.0-php8.0-fpm
          cache-to: type=inline

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
